<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-01-21 11:31

$extensionPath = t3lib_extMgm::extPath('extbase_tweaks');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_extbasetweaks_persistence_storage_typo3dbbackend' => $extensionClassesPath . 'Persistence/Storage/Typo3DbBackend.php',
);
?>